name: Build

on:
  workflow_dispatch:
    
jobs:
  builder:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] #, "macos-latest", "windows-latest"]
        python-version: ["3.8"] #, "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/conda-build
        with:
          python-version: ${{ matrix.python-version }}
