name: Build manylinux

on:
  workflow_dispatch

jobs:
  build_manylinux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build manylinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.6.0-manylinux2014_x86_64
      with:
        python-versions: 'cp38-cp38 cp39-cp39 cp310-cp310'
        pre-build-command: 'sh ./install_libs.sh'
    - name: Upload wheel artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wheel-artifacts
        path: dist/*-manylinux*.whl
  test_manylinux:
    runs-on: ubuntu-latest
    needs: build_manylinux
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Download wheel artifacts
        uses: actions/download-artifact@v3
        with:
          name: wheel-artifacts
          path: dist
      - name: Install wheels
        run: |
          ls dist
          pip install --no-index --find-links ./dist yapybrot 
      - name: Test wheels
        run: |
          pip install pytest
          pytest