name: Build

on:
  push:
    branches:
      - '*'
      - '!main'
    
jobs:
  builder:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: myenv
      - name: Install dependencies
        run: |
            conda install -c conda-forge --file requirements.txt
      - name: Build
        run: |
            pip install .
      - name: Test
        run: |
            pytest