name: Build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  builder:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/provision-with-micromamba@main
        with:
          extra-specs: python=${{ matrix.python-version }}
      - name: Build
        run: |
            pip install .
      - name: Test
        run: |
            pytest
