name: Python package

on:
  push:
    branches: [ "main", "CI" ]
  pull_request:
    branches: [ "main" ]
    
    
jobs:
  my-builder:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: myenv
      - name: Install dependencies
        run: |
            conda activate myenv
            conda info
            conda list
            conda install -c conda-forge --file requirements.txt
      - name: Build
        run: |
            conda activate myenv
            conda info
            conda list
            python setup.py install
      - name: Test
        run: |
            conda activate myenv
            conda info
            conda list
            pytest