name: Release

on:
  push:
    branches:
      - 'main'
    tags:  
       - 'v\*'

jobs:
  builder:
    name: Release (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.10"
          activate-environment: myenv
      - name: Install dependencies
        shell: bash -el {0}
        run: |
            python -m pip install --upgrade pip
            conda install -c conda-forge --file requirements.txt
      - name: Build
        run: |
            pip install .
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest
      - name: Package
        run: |
            python setup.py sdist bdist_wheel            
      - name: Publish
        env:
            TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
            TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
            ls dist
            conda info
            twine upload dist/*