name: Release
description: Build and publish wheels for Windows and MacOS along with source to PyPI

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v\*'

env:
  TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
  TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

jobs:
  release_source:
    name: Release Source
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.10"
          activate-environment: myenv
      - uses: conda-build
      - name: Package Source
        run: |
            python setup.py sdist            
      - name: Publish Source
        run: |
            twine upload dist/*.tar.gz
    
  release_wheels:
    name: Release Wheel (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: true
      matrix:
        os: ["macos-latest", "windows-latest"]
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: myenv
      - uses: conda-build
      - name: Package Wheel
        run: |
            python setup.py bdist_wheel            
      - name: Publish Wheel
        run: |
            twine upload dist/*.whl