name: Release

on:
  push:
    branches:
      - 'main'
    tags:  
       - 'v\*'

jobs:
  builder:
    name: Release (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.10"
          activate-environment: myenv
      - name: Install dependencies
        shell: bash -el {0}
        run: |
            conda install -c conda-forge --file requirements.txt
            pip install twine
      - name: Build
        run: |
            pip install .
      - name: Test
        run: |
            pytest
      - name: Package
        run: |
            python setup.py sdist bdist_wheel            
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            password: ${{ secrets.PYPI_PASSWORD }}