name: Release

on:
  push:
    branches:
      - 'main'
    tags:  
       - 'v\*'

jobs:
  builder:
    name: Release (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.10
          activate-environment: myenv
      - name: Install dependencies
        shell: bash -el {0}
        run: |
            conda install -c conda-forge --file requirements.txt
            pip install twine
      - name: Build
        shell: bash -el {0}
        run: |
            pip install .
      - name: Test
        shell: bash -el {0}
        run: |
            pytest
      - name: Package
        shell: bash -el {0}
        run: |
            python setup.py sdist bdist_wheel            
      - name: Publish
        shell: bash -el {0}
        env:
            TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
            TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
            twine upload dist/*