name: 'Conda Build'
description: 'Builds the project in a conda environment'
inputs:
  python-version:
    required: true
    default: '3.10'
runs:
  using: "composite"
  steps:
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ inputs.python-version }}
        activate-environment: myenv
    - name: Install dependencies
      run: |
        conda install -c conda-forge --file requirements.txt
      shell: bash -el {0}
    - name: Build
      run: |
        pip install .
      shell: bash -el {0}
